modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dima-dencep/online-emotes/issues"
license = "OSL-3.0"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "online_emotes"
version = "${project.version}"
displayName = "Online Emotes"
# updateJSONURL = "https://api.modrinth.com/updates/online-emotes/forge_updates.json"
authors = "dima_dencep"
credits = "NE4T0, nneewwtt, Amirhan-Taipovjan, yichifauzi"
displayURL = "https://curseforge.com/minecraft/mc-mods/online-emotes"
description = "Allows players to see each other's emotes without emotecraft installed on the server."
logoFile = "assets/online-emotes/icon.png"

[[mixins]]
config = "online-emotes.mixins.json"

[[dependencies.online_emotes]]
modId = "neoforge"
type = "required"
versionRange = "[${project.forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.online_emotes]]
modId = "minecraft"
type = "required"
versionRange = "[${project.minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.online_emotes]]
modId = "emotecraft"
type = "required"
versionRange = "[${project.emotecraft_version},)"
ordering = "AFTER"
side = "CLIENT"